# Generated by Django 5.0.2 on 2024-02-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores',
            name='bandera',
            field=models.BooleanField(default=False),
        ),
    ]
